version: 2
updates:
  # Configuration for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependabot"
    groups:
      version-updates:
        patterns:
          - "*"
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
      security-updates:
        patterns:
          - "*"
        applies-to: security-updates
        update-types:
          - "patch"
          - "minor"
  
  # Configuration for Gradle (Java)
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependabot"
    groups:
      version-updates:
        patterns:
          - "*"
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
      security-updates:
        patterns:
          - "*"
        applies-to: security-updates
        update-types:
          - "patch"
          - "minor"

  # Configuration for pip (Python)
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependabot"
    groups:
      version-updates:
        patterns:
          - "*"
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
      security-updates:
        patterns:
          - "*"
        applies-to: security-updates
        update-types:
          - "patch"
          - "minor"