CREATE USER testtest WITH PASSWORD 'testtest';
GRANT CONNECT ON DATABASE tesseradb TO testtest;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO testtest;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO testtest;

GRANT CREATE ON SCHEMA public TO testtest;