name: Gradle CI
on:
  pull_request:
    branches: [ main, release/**, hotfix/** ]
  push:
    branches: [ main ]
  workflow_dispatch:  
jobs:
  ci-pipeline:
    uses: partior-libs/controller-3p-pipelines/.github/workflows/pipeline-template-gradle-ci-tessera.yaml@feature/DSO-2754-refine-jfrog-cli-debug
    with:
      CONTROLLER-REPO: partior-libs/controller-3p-pipelines
      PROJECT-REPO: ${{ github.repository }}
      CONTROLLER-REF: feature/DSO-2754-refine-jfrog-cli-debug
    secrets: inherit