name: Security Scan
on: 
  workflow_dispatch:

jobs:
  trigger_security_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch Security Scan
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GH_REPO_READER_TOKEN }}  
          repository: partior-sec-eng/3p-security-scanning
          event-type: run_security_scan
          client-payload: '{"caller": "3p-tessera"}' 